"""Poetry is a pinned build input rather than an ambient executable."""

from __future__ import annotations

import tomllib
from collections.abc import Callable
from pathlib import Path

import pytest
from scripts.check_poetry_toolchain import (
    PoetryToolchainError,
    active_version,
    bootstrap_version,
    lock_generator_version,
    require_match,
    required_version,
)

REPO = Path(__file__).resolve().parents[1]


def test_every_poetry_surface_uses_the_project_pin() -> None:
    wanted = required_version((REPO / "pyproject.toml").read_text(encoding="utf-8"))
    assert wanted == lock_generator_version(
        (REPO / "poetry.lock").read_text(encoding="utf-8")
    )
    bootstraps = sorted(
        (REPO / ".github/bootstrap").glob("poetry-requirements-py*.txt")
    )
    assert bootstraps
    assert {
        bootstrap_version(item.read_text(encoding="utf-8")) for item in bootstraps
    } == {wanted}


@pytest.mark.parametrize(
    ("reader", "bad"),
    [
        (required_version, '[tool.poetry]\nrequires-poetry = ">=2.4"\n'),
        (lock_generator_version, "# generated by something else\n"),
        (bootstrap_version, "poetry==2.4.1\npoetry==2.3.1\n"),
    ],
)
def test_ambiguous_or_missing_versions_fail_closed(
    reader: Callable[[str], str], bad: str
) -> None:
    with pytest.raises(PoetryToolchainError):
        reader(bad)


def test_version_mismatch_is_visible_before_dependency_work() -> None:
    assert active_version("Poetry (version 2.4.1)") == "2.4.1"
    with pytest.raises(PoetryToolchainError, match="active Poetry uses Poetry 2.3.1"):
        require_match("2.4.1", "2.3.1", "active Poetry")


def test_ci_uses_the_pinned_setup_and_make_check_is_complete() -> None:
    workflow = (REPO / ".github/workflows/ci.yml").read_text(encoding="utf-8")
    makefile = (REPO / "Makefile").read_text(encoding="utf-8")
    assert "uses: ./.github/actions/setup-poetry" in workflow
    assert "pip install httpx pytest ruff" not in workflow
    assert "poetry-lock-check" in workflow
    check_recipe = next(
        line for line in makefile.splitlines() if line.startswith("check:")
    ).split("##", 1)[0]
    for target in (
        "poetry-lock-check",
        "lint",
        "format-check",
        "test",
        "package-check",
    ):
        assert target in check_recipe


def test_the_real_project_pin_is_exact_not_a_range() -> None:
    body = (REPO / "pyproject.toml").read_text(encoding="utf-8")
    poetry = tomllib.loads(body)["tool"]["poetry"]
    assert poetry["requires-poetry"] == required_version(body)
